const INVENTORY_CONSTANTS = {
  EXPIRED: 0,
  EXPIRING_THREE_DAYS: 3,
  LOW_STOCK: 1,
  MIN_RESTOCK_DAYS: 7,
  RESTOCK_AMOUNT: 2,
};

const MEAL_CONSTANTS = {
  TOTAL_MEALS: 7,
  MAX_REPEATS: 2,
  MAX_MISSING: 3,
};

const GENERATE_CONSTANTS = {
  BUDGET: 50,
  ALLOW_REPEATS: true,
  MAX_MISSING: 5,
};

const ALGORITHM_WEIGHTS = {
  BUDGET: 0.5,
  INVENTORY: 0.35,
  COMPLEXITY: 0.15,
};

const FALLBACK_METRICS = {
  COST: 3.0,
  INVENTORY_USAGE: 0.5,
};

const MEAL_PLAN_TYPES = {
  BUDGET_MAXIMIZER: "Budget Maximizer",
  INVENTORY_MAXIMIZER: "Inventory Maximizer",
  COMPLEXITY_MAXIMIZER: "Complexity Maximizer",
  BEST_OVERALL: "Best Overall",
};

module.exports = {
  INVENTORY_CONSTANTS,
  MEAL_CONSTANTS,
  GENERATE_CONSTANTS,
  ALGORITHM_WEIGHTS,
  FALLBACK_METRICS,
  MEAL_PLAN_TYPES,
};
